spring:
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/gestor-reservas
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    enabled: true
    change-log: classpath:db.changelog.xml
    contexts: ${spring.profiles.active}
  jpa:
    hibernate:
      ddl-auto: update
  cors:
    allowed-origins:
      - http://localhost:5173
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://172.21.123.13/gestor-reservas
    username: reservas
    password: Servicios.Fisei@2024
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    enabled: true
    change-log: classpath:db.changelog.xml
    contexts: ${spring.profiles.active}
  jpa:
    hibernate:
      ddl-auto: update
  cors:
    allowed-origins:
      - http://serviciosfisei.uta.edu.ec:9060