spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gestor-reservas
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    enabled: true
    change-log: classpath:db.changelog.xml
    contexts: ${spring.profiles.active}
  jpa:
    hibernate:
      ddl-auto: update

#   Base de datos local
#   url: jdbc:mysql://localhost:3306/gestor-reservas
#   usename: root
#   password: root

#   Desarrollo Cloud
#   url: jdbc:mysql://34.174.88.52/gestor-reservas
#   username: root
#   password: root

#   Desarrollo
#   url: jdbc:mysql://hatunsoft.uta.edu.ec/gestor-reservas
#   usename: laravel
#   password: HatunSoft@2023

#   Producción
#   url: jdbc:mysql://172.21.123.13/gestor-reservas
#   username: reservas
#   password: Servicios.Fisei@2024