name: CI

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Set environment variables
      run: echo "SPRING_PROFILES_ACTIVE=$(if [[ $GITHUB_REF == 'refs/heads/develop' ]]; then echo 'dev'; else echo 'prod'; fi)" >> $GITHUB_ENV
